
CREATE TABLE [dbo].[Settlement](
	[SettlementID] [nchar](50) NOT NULL,
	[BusinessDate] [datetime] NOT NULL,
	[SettlementPlayerNo] [nvarchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[SettlementID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


